[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/art/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
