name: MERN Stack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run NPM ci
        run: npm ci

      - name: Install dependencies
        run: |
          npm install

      - name: Build server
        run: |
          cd server/ 
          npm install
          npm run build

      - name: Build ui
        run: |
          cd ui/ 
          npm install
          npm run build

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript", "python"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
