name: MERN Stack CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]  # Updated Node versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install root dependencies
        run: npm ci  # Faster and more reliable

      # --- Build & Test Server ---
      - name: Install Server Dependencies
        run: |
          cd server
          npm ci

      - name: Build Server
        run: |
          cd server
          npm run build

      - name: Run Server Tests
        run: |
          cd server
          npm test

      # --- Build UI ---
      - name: Install UI Dependencies
        run: |
          cd ui
          npm ci

      - name: Build UI
        run: |
          cd ui
          npm run build

  analyze:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
